name: CI Security Scan
on: [push]

jobs:
  trivy-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin

      - name: Run Trivy Scan
        run: |
          trivy fs . --format json --output trivy-results.json --exit-code 0

      - name: Send Results to Platform
        run: |
          python3 -c "
          import json, urllib.request

          with open('trivy-results.json') as f:
              trivy_data = json.load(f)

          payload = json.dumps({
              'repo_name': 'test-vulnerable-app',
              'branch': 'main',
              'commit_sha': '$GITHUB_SHA',
              'trivy_results': trivy_data
          }).encode('utf-8')

          req = urllib.request.Request(
              'https://nuncupative-ocie-unmodishly.ngrok-free.dev/api/scan/upload/',
              data=payload,
              headers={
                  'Authorization': 'Token 2f8eb44b90256369f129393bc870f2054c43f193',
                  'Content-Type': 'application/json'
              }
          )
          response = urllib.request.urlopen(req)
          print(response.read().decode())
          "
