name: CI Security Scan
on: [push]

jobs:
  trivy-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin

      - name: Run Trivy Scan
        run: |
          trivy fs . --format json --output trivy-results.json --exit-code 0

      - name: Send Results to Platform
        run: |
          TRIVY_JSON=$(cat trivy-results.json)
          curl -X POST https://nuncupative-ocie-unmodishly.ngrok-free.dev/api/scan/upload/ \
            -H "Authorization: Token 1b1063dc93cfe7f292bcecd61ebdde6b38bd67a4db4a4d45a4843e86c487612b" \
            -H "Content-Type: application/json" \
            --data-raw "{\"repo_name\": \"test-vulnerable-app\", \"branch\": \"main\", \"commit_sha\": \"$GITHUB_SHA\", \"trivy_results\": $TRIVY_JSON}"
